version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - exhaustive
    - fatcontext
    - gocognit
    - gocritic
    - gomodguard_v2
    - gosec
    - intrange
    - makezero
    - musttag
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - wastedassign

  settings:
    errcheck:
      check-type-assertions: true

    exhaustive:
      check:
        - switch
        - map

    gocognit:
      min-complexity: 20

    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false

    gomodguard_v2:
      blocked:
        - module: github.com/golang/protobuf
          recommendations:
            - google.golang.org/protobuf
          reason: "see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules"
        - module: github.com/satori/go.uuid
          recommendations:
            - github.com/google/uuid
          reason: "satori's package is not maintained"
        - module: github.com/gofrs/uuid
          recommendations:
            - github.com/gofrs/uuid/v5
          reason: "gofrs' package was not go module before v5"

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    nolintlint:
      allow-no-explanation: [gocognit]
      require-explanation: true
      require-specific: true

    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx

  exclusions:
    rules:
      - source: "//noinspection"
        linters: [gocritic]
      - path: "_test\\.go"
        linters:
          - bodyclose
          - errcheck
          - gosec
          - noctx

issues:
  max-same-issues: 50

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - gci

  settings:
    gofmt:
      simplify: true

    gofumpt:
      module-path: github.com/akgbytes/ylx
      extra-rules: true

    goimports:
      local-prefixes:
        - github.com/akgbytes/ylx

    gci:
      custom-order: true
      no-inline-comments: true
      no-prefix-comments: true
      sections:
        - standard
        - default
        - prefix(github.com/akgbytes/ylx)
        - blank
        - dot
        - alias
        - localmodule
